# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.cache/wt [current_project]
set_property parent.project_path /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_max11046_0_SHDN_CONVST_0/design_1_axi_max11046_0_SHDN_CONVST_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_max11046_0_SHDN_CONVST_0/design_1_axi_max11046_0_SHDN_CONVST_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_max11046_0_SHDN_CONVST_0/design_1_axi_max11046_0_SHDN_CONVST_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_max11046_0_CS_RD_0/design_1_axi_max11046_0_CS_RD_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_max11046_0_CS_RD_0/design_1_axi_max11046_0_CS_RD_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_max11046_0_CS_RD_0/design_1_axi_max11046_0_CS_RD_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_5/design_1_axi_gpio_0_5_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_5/design_1_axi_gpio_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_5/design_1_axi_gpio_0_5.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_7/design_1_axi_gpio_0_7_board.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_7/design_1_axi_gpio_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_7/design_1_axi_gpio_0_7.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/sources_1/bd/design_1/design_1.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/constrs_1/new/PMOD.xdc
set_property used_in_implementation false [get_files /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/constrs_1/new/PMOD.xdc]

read_xdc /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/constrs_1/new/Petaluma.xdc
set_property used_in_implementation false [get_files /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/constrs_1/new/Petaluma.xdc]

read_xdc /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/constrs_1/new/Analog_Out.xdc
set_property used_in_implementation false [get_files /home/tux/projects/HoloLensRUB/HW_FestoHoloLens/LinuxSys.srcs/constrs_1/new/Analog_Out.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
